### ISSUE TITLE
Subtasks mix main and sub tasks titles

### ISSUE THREAD

**Issue by judicandus** [wayneashleyberry/wunderlist-cli#112]
On my Windows 10 machine, when I execute:
`wunderline add 'Run a marathon' --subtask 'Train for the marathon' --subtask 'Register for the marathon'`

It creates a task in wunderlist named: **'Run a marathon' for the marathon' for the marathon'**

And two subtasks named; **'Train** and **'Register**

It seems to be a simple problem with the quotes. I stick to creating subtasks with single words so the problem wouldn't arise.

I'll also take this opportunity to thank you for such an amazing tool. It's a life saver.

Best Regards,

Dan

**Comment by Thor77** [comment]
Hey Dan,

unfortunately I can't reproduce your issue on my system (ArchLinux).
Are you using Windows builtin cmd.exe or smth else? It's probably an issue with your terminal and correct quoting. What happens if you use double instead of single quotes?

**Comment by judicandus** [comment]
Thank you so much for instant reply!

I'm using Windows builtin cmd.exe . I tried it with the double quotes and it worked just fine. 
There probably is some function when using several single quotes in a batch script that I am unaware of.

Sorry for not testing such simple change beforehand.

Thank you,
