### ISSUE TITLE
Invalid DateTime for Reminder

### ISSUE THREAD

**Issue by bhman792** [wayneashleyberry/wunderlist-cli#120]
I've tried every format I can think of and nothing is working.  What is the right format for datetime?

**Comment by Thor77** [comment]
The correct format is `YYYY-MM-DD HH:mm`. If there's no valid reminder datetime given, it will fallback to the due date (if given).

I guess we should clarify that in the error message.

**Comment by Thor77** [comment]
If there's anything else to clarify, feel free to reopen :)
