### ISSUE TITLE
Assigning Tasks to Other Users

### ISSUE THREAD

**Issue by bhman792** [wayneashleyberry/wunderlist-cli#121]
Is it possible using Wunderline to use the feature in Wunderlist where you can assign a task to another user?

**Comment by Thor77** [comment]
It's currently not implemented in wunderline.

It's possible to set it via the `asignee_id`-attribute when creating/updating tasks, though [ref](https://developer.wunderlist.com/documentation/endpoints/task).

**Comment by bhman792** [comment]
Is there any chance it could be added? :)

**Comment by Thor77** [comment]
I'll take a look at it in the next few days.

**Comment by bhman792** [comment]
Any Luck?

**Comment by Thor77** [comment]
Nope, didn't get to it. I'm trying to get it working right now, though.

Would you prefer to mention an assignee by it's id or by it's name/email?
If opting for the first option, we should probably add a new command to list available users.

**Comment by Thor77** [comment]
If you have any further suggestions, please comment in #122
