### ISSUE TITLE
Display a given list

### ISSUE THREAD

**Issue by dhaffner** [wayneashleyberry/wunderlist-cli#29]
Similar to `wunderline search [query]`, a command to show tasks from a given list. Not sure about the command name. Some ideas:

These would find and display tasks from a list whose name is "My Private Tasks"
- `wunderline view private` 
- `wunderline list private`
- `wunderline search --list private`

I'd be more than happy to implement this, just curious on your thoughts. Cheers for the nice CLI!

**Comment by wayneashleyberry** [comment]
Hey @dhaffner - I might have time to get to this this week, but if you'd like to send a pull request that would be great!

Cheers

**Comment by wayneashleyberry** [comment]
Thanks for the PR @dhaffner, I've merged, made a few changes and published :)
