### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by wayneashleyberry** [wayneashleyberry/wunderlist-cli#49]
Looks like folders have been added to the API, yay :)

https://developer.wunderlist.com/documentation/endpoints/folder

**Comment by shawnroos** [comment]
Good thing! [There's demand](http://www.producthunt.com/tech/wunderline#comment-115594)

**Comment by Thor77** [comment]
Are there any specific plans on how to implement this feature?
Should folders show up in task-listings?
Schould searching a list include folders (maybe an `--recursive`-option)?
Should there be a new `folders`-command to list their tasks, remove them and create new ones?

**Comment by alexandrebarbaruiva** [comment]
@wayneashleyberry assign me this task! I'll try to finish it sunday

**Comment by wayneashleyberry** [comment]
I can't assign you until you're a collaborator @alexandrebarbaruiva, you're welcome to send a pull request at any time though :)

**Comment by alexandrebarbaruiva** [comment]
Ok, will do 😁
