### ISSUE TITLE
Add support for notes

### ISSUE THREAD

**Issue by rnc** [wayneashleyberry/wunderlist-cli#56]
It looks like the endpoint exists

https://developer.wunderlist.com/documentation/endpoints/note

**Comment by wayneashleyberry** [comment]
Will have a look into this @rnc, I don't think it should be on by default, maybe there should be a `--notes` flag or something? How do you see this working?

**Comment by rnc** [comment]
Hi! Yes a `--notes` would work quite well for small sections of text. Perhaps a `--notesfile` to accept input from text file?

**Comment by wayneashleyberry** [comment]
I was thinking about displaying notes, wasn't even considering creating tasks with notes haha

**Comment by wayneashleyberry** [comment]
Closed in https://github.com/we-are-next/wunderline/pull/58
