### ISSUE TITLE
Due date listings don't respect the year

### ISSUE THREAD

**Issue by tolleiv** [wayneashleyberry/wunderlist-cli#59]
Hi,
I'm using Wunderlist to keep track of todos which are recurring on a yearly or bi-yearly basis. So I've a lot of dates in the far future. 
Unfortunately "wunderline list" doesn't show the year of the due date - that's more a minor problem but still not too nice. The second problem is that the "wunderline week" command also lists all todos which are due in 1 year.
Would be great if you could have a look.

Steps to reproduce:
- Create a task with due date in 365 days, run one of the commands mentioned and you'll see

Besides that thank you for sharing this great tool :)

Cheers

**Comment by wayneashleyberry** [comment]
Closed in https://github.com/we-are-next/wunderline/pull/60
