### ISSUE TITLE
Fixed column width truncating title

### ISSUE THREAD

**Issue by purinda** [wayneashleyberry/wunderlist-cli#68]
First, I am thanking you for spending time to build this brilliant CLI for the wunderlist! very useful.

I started using wunderline today and found that task title gets truncated when you have tasks title running for more than 60 characters, since most of my tasks are running past this limit, I couldn't pretty much list my daily TODO tasks effectively. 

An example:
#### Current implementation

![60_char_limit](https://cloud.githubusercontent.com/assets/3181510/11930933/4b3e4024-a83c-11e5-9e63-2e1546499027.png)
#### What I am proposing

![dynamic_column_width_fix](https://cloud.githubusercontent.com/assets/3181510/11930954/7b9eb06e-a83c-11e5-9d56-fcd1e5f009b9.png)

PR for the issue can be found here 
https://github.com/we-are-next/wunderline/pull/67

**Comment by purinda** [comment]
@wayneashleyberry Thanks for merging the PR.

**Comment by wayneashleyberry** [comment]
My pleasure, thanks for the code @purinda, I added a little space just to make sure the other columns all fit :)
