### ISSUE TITLE
Force ES6 support

### ISSUE THREAD

**Issue by naps62** [wayneashleyberry/wunderlist-cli#69]
I tried to install this under node 0.10.40, which was the version I had installed at the time. Since that version doesn't support ES6 syntax, which apparently is used here, I got this error:

```
$ wunderline add "Hello, World"

/home/naps62/.nvm/v0.10.40/lib/node_modules/wunderline/wunderline-add.js:146
        stdin().then(data => {
                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I believe this can be fixed by adding an `engine` section to `package.json`?

**Comment by juliankay** [comment]
Hey @naps62 did you get this working? I have the same issue

**Comment by naps62** [comment]
@juliankay I got it working by installing node v4 (I'm using nvm so it's just a matter of running `nvm install 4.2.4`)

But right now I have to manually switch to this version when I want to use wunderline, since I need 0.12 to be the default version most of the time

**Comment by juliankay** [comment]
thanks @naps62 that worked a treat! :+1:

**Comment by wayneashleyberry** [comment]
Thanks @naps62, updated the `package.json` in https://github.com/we-are-next/wunderline/commit/7c68c14bf1c94c293305251685bdb9337e315c76.
