### ISSUE TITLE
Question: possible to set "Remind me" date?

### ISSUE THREAD

**Issue by JayBrown** [wayneashleyberry/wunderlist-cli#72]
Love wunderline, just love it. Thank you very much. Is there by any chance a way to set a "Remind me" date? It doesn't seem to be documented. (Or is it impossible?)

**Comment by wayneashleyberry** [comment]
Hi @JayBrown :)

Firstly, thanks! I'm so glad you're enjoying Wunderline!

It is possible to create tasks with due dates, if that's what you're referring to?

``` sh
$ wunderline help add

  Usage: wunderline-add [task]

  Add a task to your inbox

  Options:

    -h, --help         output usage information
    -l, --list [name]  Specify a list other than your inbox
    --today            Set the due date to today
    --tomorrow         Set the due date to tomorrow
    --due [date]       Set a specific due date
    --note [note]      Attach a note to the new task
    -o, --open         Open Wunderlist on completion
    -s, --stdin        Create tasks from stdin

```

``` sh
$ wunderline add "Hello, World!" --tomorrow
```

**Comment by JayBrown** [comment]
Thank you for the quick reply. I'm afraid I mean something different… see the screenshot here: http://i.imgur.com/qH0HlNZ.png

You can set the due date, which wunderline manages fine (today, tomorrow and in date format), and right below that you can also set the "Remind me" date (format: date & time), which is what I mean. So a wunderline CLI command in this respect would maybe look like:

`wunderline add "Task to do" --list "List name" --date 2016-02-25 --remind 2016-02-19 --note "Text to go into note field"`

(Note: it's in quoted form with double quotes, but of course you can also use single quotes ' text ' which you would need if you add wunderline into an AppleScript via **do shell script**.)

So there is a difference between **due-date** and **remind-me-date**: one is your deadline to finish the task, the other is the date Wunderlist will remind you to finish that task.

By the way: In Wunderlist you can also create a **subtask** and a **comment**. I don't need these two things in wunderline, but maybe other users might.

**Comment by wayneashleyberry** [comment]
Ah okay, I see what you mean. I'll have a look into it, should be pretty simple :)

I doubt I'll add subtasks and comments, just because I think a command-line wouldn't be a great interface for doing that :)

**Comment by JayBrown** [comment]
Oh, that's great. I forgot to add that you can also set the time for the reminder, not only the date, so the syntax could be something like
`--remind 2016-02-19-17-30-15`
for date 19th of February 2016, time 17:30:15 (5:30 PM and 15 seconds).

**Comment by Thor77** [comment]
The API doesn't implement that feature yet [_ref_](https://developer.wunderlist.com/documentation/endpoints/task)

**Comment by Thor77** [comment]
Reminders are now implemented as a [seperate endpoint](https://developer.wunderlist.com/documentation/endpoints/reminder). Please reopen @wayneashleyberry
