### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by rnc** [wayneashleyberry/wunderlist-cli#80]
If I have a list with e.g. `Current` and `current` listing on `Current` should not return `current`

**Comment by Thor77** [comment]
Why do you think so?
I think most people expect a search to be case-insensitive and I'm for keeping it like that.
@wayneashleyberry what to you think?

**Comment by wayneashleyberry** [comment]
I far prefer case insensitivity, @rnc is there a specific reason you need an exact match?

**Comment by rnc** [comment]
@wayneashleyberry  I understand people have differing opinions on this. I am simply used to case sensitivity. If I recall (its a while since I've tried it)  I think part of the problem was I had added a list entitled "Current" via the app/web api but there was some inconsistencies when attempting to list/modify it via the CLI. I wonder if a configuration option would help here?

**Comment by Thor77** [comment]
Can you elaborate on your specific problem?
I don't really see the problem, because when adding a task on a specific list via wunderline, the list-name is [converted to lowercase](https://github.com/wayneashleyberry/wunderline/blob/master/wunderline-add.js#L61) and listing of tasks on a specific list is currently not supported.

**Comment by rnc** [comment]
@Thor77  @wayneashleyberry  As having multiple lists differing only in case is such a edge-case I would suggest just closing this?

**Comment by wayneashleyberry** [comment]
I actually wouldn't mind implementing this in a similar manner as `smartcase` in vim.

> When 'ignorecase' and 'smartcase' are both on, if a pattern contains an uppercase letter, it is case sensitive, otherwise, it is not. For example, /The would find only "The", while /the would find "the" or "The" etc. (http://vim.wikia.com/wiki/Searching)

So by default search's are case insensitive, unless the search term contains an uppercase character. How's that sound @rnc?

**Comment by rnc** [comment]
@wayneashleyberry  +1

**Comment by rnc** [comment]
@Thor77  I wonder if similar should apply to the search facility. From what I can see currently it is also case insensitive but is also using a fuzzy matching algorithm which means searching for e.g. RCM will return
"Update RCM"
and
"Handle releasing in config and new document"

The latter is a bit unintuitive. Either an explicit regexp of ability to quote would be useful. (Perhaps this is better as a separate issue?)

**Comment by Thor77** [comment]
Yeah, please open an seperate issue for the search-command. We should extract this functionality into an own function then to provide a consistent experience throughout the application.
