### ISSUE TITLE
auth doesn't seem to work on OS X 10.9.4

### ISSUE THREAD

**Issue by michaelhauser** [wayneashleyberry/wunderlist-cli#87]
I run 'wunderline auth' and enter my client id and access token (as generated on the Wunderlist app page), and then I try to run a command like 'wunderline inbox' and I get "Wunderline needs application credentials before continuing..."
This is with node 6.2.2 on OS X 10.9.4.

**Comment by jmcclell** [comment]
Upgrade to version >=/4.4.1. I had the same issue and discovered it was an issue with a breaking change in a dependent library. I submitted PR #86  to fix the version constraints to avoid the breaking change and it was accepted and merged.

**Comment by michaelhauser** [comment]
Version 4.4.1 is already installed, as is inquirer 1.0.3.

Michaels-iMac:node_modules hauser$ npm list inquirer
hauser@1.0.0 /Users/hauser
└─┬ wunderline@4.4.1
  ├── inquirer@1.0.3
  └─┬ vorpal@1.11.2
    └── inquirer@0.11.0

**Comment by Thor77** [comment]
Can you still reproduce this?

**Comment by Thor77** [comment]
If I don't receive feedback on this from @michaelhauser in 3 days (20 days passed), I will close this.

**Comment by Thor77** [comment]
Eh, yeah. 3 days passed. Feel free to reopen if you can still reproduce this.
