### ISSUE TITLE
Display bug: list name that starts with emoji

### ISSUE THREAD

**Issue by crispgm** [wayneashleyberry/wunderlist-cli#95]
![image](https://cloud.githubusercontent.com/assets/1425636/18190873/451148ec-70f8-11e6-9539-aea739f49a5c.png)

Note the last item ":book:Reading", on macOS.

**Comment by wayneashleyberry** [comment]
hey @crispgm, that's strange... did you put a space between the emoji and title?

**Comment by crispgm** [comment]
@wayneashleyberry Nope, there is no spaces between.

**Comment by Thor77** [comment]
It's probably a problem with your font/terminal setup and not with wunderline.
Can you confirm it just happens with wunderline? (For example, if `echo 📖Reading` shows up right)

**Comment by crispgm** [comment]
![image](https://cloud.githubusercontent.com/assets/1425636/18792268/6088f07e-81e8-11e6-813c-d34bfbc0572a.png)

@Thor77 it this confirmed?

**Comment by Thor77** [comment]
That confirms the issue is with your font/terminal setup and not with wunderline :)

**Comment by crispgm** [comment]
@Thor77 Thank you. Not a bug, closed.
