### ISSUE TITLE
Problem on Ubunu 16.04

### ISSUE THREAD

**Issue by elmerehbi** [wayneashleyberry/wunderlist-cli#98]
I tried installing but it doesn't seem to work:

```
sudo npm instal -g wunderline
wunderline auth
```

Last command returns:

> /usr/bin/env: ‘node’: No such file or directory

A friend tried and he said it works but with sudo. It returns the same error for me.

npm list returns the following:

```
npm list inquirer        
/home/usernam
└── (empty)

npm ERR! code 1
```

**Comment by wayneashleyberry** [comment]
Hi @elmerehbi, having not used Ubuntu for a while I haven't encountered this error before. Out of interest which version of node/npm are you using and have you successfully installed other node binaries through npm?

You definitely shouldn't need to use sudo, maybe someone with more Ubuntu experience could shed some light on that.

To see if wunderline installed globally you can use the following command:

``` sh
npm ls -g --depth=0
```

**Comment by elmerehbi** [comment]
@wayneashleyberry 

nodejs: v4.2.6
npm: 3.5.2

I am aware of this (about sudo). I don't use anything other than Ubuntu.
I asked the friend to try it on his system and I was passing it that it worked for him with sudo (i understand that's not what should be used for the regular user) but not without it.

I don't use nodejs/npm. I remember I had problems with it before trying to install a package.

```
~ npm ls -g --depth=0
/usr/local/lib
└── wunderline@4.4.2
```

**Comment by js94x** [comment]
@elmerehbi 
I solved it with this workaround:
ln -s /usr/bin/nodejs /usr/bin/node

It happens because wunderline´s binary use `#!/usr/bin/env node`. 
/usr/bin/env search through the environment variable $PATH and doesn´t find a binary called node.

**Comment by elmerehbi** [comment]
Perfect. That works. Thank you
